### ISSUE TITLE
[问题]无法打开笔记

### ISSUE THREAD

**Issue by senkawu** [rxliuli/joplin-vscode-plugin#1]
你好，我在vscode中配置好了插件，可以看到笔记的标题了。但是无法打开。

vscod版本: 1.46.1 (user setup)

Joplin 1.0.220 (prod, win32)

**Comment by rxliuli** [comment]
需要使用预览版本

吴诺克 <notifications@github.com> 于 2020年6月27日周六 下午4:35写道：

**Comment by rxliuli** [comment]
https://github.com/laurent22/joplin/releases/tag/v1.0.224
