### ISSUE TITLE
Feature request: pasting images/files directly

### ISSUE THREAD

**Issue by hexclover** [rxliuli/joplin-vscode-plugin#10]
Thanks for this wonderful extension.

Now I think it would be nice to allow pasting images/files from clipboard directly. Will we have this feature?

Thank you!

**Comment by rxliuli** [comment]
Not yet, I can try to implement it later

**Comment by rxliuli** [comment]
Now, you can use the latest v0.1.7
1. Select the picture to upload from the file manager (ctrl+alt+e)
2. Upload pictures from the clipboard (ctrl+alt+u)

https://github.com/rxliuli/joplin-vscode-plugin/releases/tag/v0.1.6
