### ISSUE TITLE
Cannot open Attachments

### ISSUE THREAD

**Issue by Awbmilne** [rxliuli/joplin-vscode-plugin#12]
he  primary reason I havent switched to using VScode for editing my Joplin Notes in the Fact that I attach a large amount of files for my School Note. I use Joplin to organize them and allow me to easy find and access them. This is easy from the Joplin Editor.

I would like to be able to have easy access to the files attached to notes. Either by just clicking on them, or something similair...

~_I would like to try to make this addition myself._~
edit: @rxliuli knows the code far better than me 

~See Pull Request (Not Created Yet)~

**Comment by rxliuli** [comment]
If you want to be able to view attachments, then all attachments already have local files when opened with vscode, you can find and open them (maybe a more convenient operation is needed, I basically only attach pictures)
There are two ideas
1. List all resources in the sidebar
2. Select the resource part in markdown, and then open it in the file browser through the command
3. Click the link in preview to open it

**Comment by rxliuli** [comment]
I am trying to implement the first way

https://github.com/rxliuli/joplin-vscode-plugin/blob/master/src/model/ResourceProvider.ts

The third method may be related to markdown rendering, which may be similar to this pr

https://github.com/rxliuli/joplin-vscode-plugin/pull/8

But if you want to open it through `ctrl+click` in the editor, then you need to consider the lsp-related api

https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-sample
https://stackoverflow.com/questions/63753640/is-there-a-way-to-customize-the-link-bounce-logic-in-vscode

**Comment by Awbmilne** [comment]
After Messing around with the Plugin more... I have a more specific question regarding the Attachment and Local-Link mechanism.

**On one hand:**\
When Opening Attached files (A `Video.mkv` for example), The Plugin seems to transform the Joplin Link `[Video.mkv](:/HASH.mkv)` to a local file link `[Video.mkv](resources/HASH.mkv)`... This seems work inside the Markdown editor, but once you open the Markdown preview (for reading/previewing notes), the Link stays the same but no longer works...? This may be an issue with some of my link-opening configurations, but is a peculiar issue either way.

![Trying to Open  mkv file](https://user-images.githubusercontent.com/50780746/95496004-35499780-096e-11eb-9515-12499976951c.gif)


**On the other hand:**\
When Opening links to other Joplin Notes, The plugin neglects to transform the Link and leaves it as the plain hash in the Markdown Editor `[Note B](:/HASH)`.... It is not possible to open this Link in the Markdown Editor. When you open the Markdown Preview, The Link is transformed to a Joplin-Plugin command link `vscode://rxliuli.joplin-vscode-plugin/open?id=HASH`.

![Trying to Open Linked Note File](https://user-images.githubusercontent.com/50780746/95497433-501d0b80-0970-11eb-9c0f-717698d6f76c.gif)

Both of these Seem to be great systems for 1 of the 2 cases.
But obviously, it would be ideal for both to work for both types of Links.

How do the Link handling mechanisms for attached file and cross note reference differ internally? And is there an easy way to combine them to be more uniform?

**Comment by rxliuli** [comment]
Ctrl+click in the editor and click in markdown preview are two different processing mechanisms

In the editor, the jump is handled through [lsp](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide), which may be [vscode go to](https://code.visualstudio.com/api/references/vscode-api#DeclarationProvider)

The click processing steps in markdown preview are
1. Modify the rendering of special links in markdown to `vscode://rxliuli.joplin-vscode-plugin/*`, related api: [markdown render](https://code.visualstudio.com/api/extension-guides/markdown-extension)
2. Monitor the click of `vscode://rxliuli.joplin-vscode-plugin/*` in vscode for special processing, related api: [url handler](https://code.visualstudio.com/api/references/vscode-api#UriHandler)

**Comment by rxliuli** [comment]
At present, I use the second method to deal with joplin internal reference links, but not in the editor. The problem I encountered is: https://stackoverflow.com/questions/63753640/is-there-a-way-to-customize-the-link-bounce-logic-in-vscode

**Comment by rxliuli** [comment]
![image](https://user-images.githubusercontent.com/24560368/95528904-071a9500-0a0c-11eb-8812-424d82ff9025.png)
Obviously, I need to perform special rendering on resource/*, which is handled like joplin internal links

**Comment by rxliuli** [comment]
v0.1.8

- Joplin resource link markdown preview
- Image upload
- todo list show specify icon

[joplin-vscode-plugin-0.1.8.zip](https://github.com/rxliuli/joplin-vscode-plugin/files/5354762/joplin-vscode-plugin-0.1.8.zip)

**Comment by Awbmilne** [comment]
v0.1.8 

Amazing improvement! Much appreciated...

There is still an issue with opening attachments from the Markdown Preview though:\
![Cannot Open Attachment From Viewer](https://user-images.githubusercontent.com/50780746/95634593-4078f200-0a58-11eb-8548-7393f7252818.gif)

**Comment by Awbmilne** [comment]
Also... This doesnt seem to allow you to Edit attachments.

I Made a `test.txt` file with:
```
Test Tnoteest
```

I attached this file using the Joplin Desktop app, and syncronized my remote.

I then opened the attachment in Joplin-VScode, edited it to:
```
Test Test Test
```
Saved file, Synchronized in the Joplin app... And the file didnt upload on the Remote (Since it didnt know it changed)

I asssume the API must be used to make these type of File edits...

![image](https://user-images.githubusercontent.com/50780746/95635374-3ce66a80-0a5a-11eb-9fea-ca071fc06aaa.png)

*I tried editing to Note also, so that it forces an update of the `.md` file, but this didnt force the attachment sync*

**Comment by rxliuli** [comment]
![test (1)](https://user-images.githubusercontent.com/24560368/95644287-3a325680-0ae8-11eb-945c-d66eb6aa8b42.gif)
![test (2)](https://user-images.githubusercontent.com/24560368/95644326-854c6980-0ae8-11eb-8848-15d3bc0023a4.gif)

I have not reproduced the two problems you mentioned here, but you can try the following operations to try to solve the problem
1. Update the version of Joplin to the latest
2. View the markdown preview in joplin and click txt edit to see if it will be synchronized.

**Comment by rxliuli** [comment]
I packaged a v0.1.9 and added some logs. Can you see the following two messages when you click it?
![image](https://user-images.githubusercontent.com/24560368/95647734-547a2d80-0b04-11eb-907e-7d10c7e0afae.png)

[joplin-vscode-plugin-0.1.9.zip](https://github.com/rxliuli/joplin-vscode-plugin/files/5358532/joplin-vscode-plugin-0.1.9.zip)

**Comment by Awbmilne** [comment]
> Also... This doesnt seem to allow you to Edit attachments.

Sorry, I was a little vague with my statement and my images...

What I meant by "Cannot edit", was that I cannot edit and have the Files sync to a Joplin sync target properly.\
The picture above shows me editing the Text File on the local server (`Test Test Test`) and viewing on the remote sync target (`Test Test`). The later should update when I use the "Synchronize" function in the Joplin Desktop App, but the Joplin app doesnt seem to recognize this.

I assume this is due to the way the Desktop Joplin App handles editing (creating a temporary file and watching for edits and updating the internal resources itself), There may be an extra step of listing the files it needs to check when syncing the next time (or something similair). Id imagine there is a way to follow this editing scheme with the Joplin API.

**Comment by rxliuli** [comment]
> > Also... This doesnt seem to allow you to Edit attachments.
> 
> Sorry, I was a little vague with my statement and my images...
> 
> What I meant by "Cannot edit", was that I cannot edit and have the Files sync to a Joplin sync target properly.
> The picture above shows me editing the Text File on the local server (`Test Test Test`) and viewing on the remote sync target (`Test Test`). The later should update when I use the "Synchronize" function in the Joplin Desktop App, but the Joplin app doesnt seem to recognize this.
> 
> I assume this is due to the way the Desktop Joplin App handles editing (creating a temporary file and watching for edits and updating the internal resources itself), There may be an extra step of listing the files it needs to check when syncing the next time (or something similair). Id imagine there is a way to follow this editing scheme with the Joplin API.

If joplin itself does not properly synchronize the modification of internal resources, then the plug-in will not handle this problem, because I don’t want to maintain a set of update logic when files change outside of joplin

**Comment by Awbmilne** [comment]
The Log messages show up, but the file doesnt open... 🤔

_joplin-vscode-plugin_:
```
[info] uriHandler: {"$mid":1,"external":"vscode://rxliuli.joplin-vscode-plugin/resource?id%3D6df0655ed0fe4c6184c42431e5e0f5c3","path":"/resource","scheme":"vscode","authority":"rxliuli.joplin-vscode-plugin","query":"id=6df0655ed0fe4c6184c42431e5e0f5c3"}
[info] open file: 6df0655ed0fe4c6184c42431e5e0f5c3.txt
```

Just for stupidity sake... I made sure the `...\joplin-desktop\resources\6df0655ed0fe4c6184c42431e5e0f5c3.txt` file exists.

**Comment by rxliuli** [comment]
> The Log messages show up, but the file doesnt open... 🤔
> 
> _joplin-vscode-plugin_:
> 
> ```
> [info] uriHandler: {"$mid":1,"external":"vscode://rxliuli.joplin-vscode-plugin/resource?id%3D6df0655ed0fe4c6184c42431e5e0f5c3","path":"/resource","scheme":"vscode","authority":"rxliuli.joplin-vscode-plugin","query":"id=6df0655ed0fe4c6184c42431e5e0f5c3"}
> [info] open file: 6df0655ed0fe4c6184c42431e5e0f5c3.txt
> ```

The plug-in uses the npm package open to open the file. Can you test whether it works correctly on your computer?
unit test

![test (3)](https://user-images.githubusercontent.com/24560368/95664357-bc1e9000-0b79-11eb-9955-dea4c3614a51.gif)

https://github.com/rxliuli/joplin-vscode-plugin/blob/66b1535e6abeef4022143bc0c2a129b0331d2f1c/test/util/openFileByOS.test.ts#L4

> ref: https://www.npmjs.com/package/open

**Comment by rxliuli** [comment]
v0.1.10 fixed
