### ISSUE TITLE
Editing Resources Now Possible with Joplin API

### ISSUE THREAD

**Issue by Awbmilne** [rxliuli/joplin-vscode-plugin#15]
Laurent Has recently added support for editing resources through the API.
This could solve the issues with resource edits not syncronizing with Joplin Sync targets.
</br>
![image](https://user-images.githubusercontent.com/50780746/97610178-eb8f2280-19ea-11eb-8dad-6862f5a7f94f.png)

**Comment by rxliuli** [comment]
I will try to access it this weekend

Austin Milne <notifications@github.com> 于 2020年10月30日周五 上午1:32写道：

**Comment by rxliuli** [comment]
Waiting for Joplin Resource Action related api to solve the problem of automatically using system programs to open resources

ref link: https://discourse.joplinapp.org/t/hope-to-add-api-to-return-to-joplin-basic-info-includes-installation-directory/11981/11?u=rxliuli

**Comment by Awbmilne** [comment]
Commit with External Resource Editing Service Changes in Joplin v1.3.18:
https://github.com/laurent22/joplin/commit/d25fa796c09e8274283780ad5ee03afd1560a5e9

API Watch (Without Opening) changes in Joplin v1.4.7
https://github.com/laurent22/joplin/commit/83b175bb5b9fac7afff0cd56afa6b3f438bbb0ae

**Comment by rxliuli** [comment]
> Commit with External Resource Editing Service Changes in Joplin v1.3.18:
> [laurent22/joplin@d25fa79](https://github.com/laurent22/joplin/commit/d25fa796c09e8274283780ad5ee03afd1560a5e9)
> 
> API Watch (Without Opening) changes in Joplin v1.4.7
> [laurent22/joplin@83b175b](https://github.com/laurent22/joplin/commit/83b175bb5b9fac7afff0cd56afa6b3f438bbb0ae)

v1.4.* also contains some rest api issues, and some major changes are also implied, so it may take some time to modify, currently I am still modifying [joplin-api](https://github.com/rxliuli/joplin-api) to support v1.4.* api changes

ref link: https://discourse.joplinapp.org/t/pre-release-1-4-is-now-available-for-testing/12247/

**Comment by rxliuli** [comment]
It seems that there are still some problems with Joplin's modified automatic synchronization function, which is necessary for the realization of this function. Waiting for @laurent22's reply

ref: https://discourse.joplinapp.org/t/pre-release-1-4-is-now-available-for-testing-updated-14-11-20/12247/63

**Comment by rxliuli** [comment]
As of the release of the official version of v1.4.18, there are still problems with synchronization after resource modification, which means that the modified attachment resource only takes effect locally, but it is not synchronized to the remote end.

ref link: https://discourse.joplinapp.org/t/pre-release-1-4-is-now-available-for-testing-updated-23-11-20/12247/90?u=rxliuli

**Comment by rxliuli** [comment]
The resources are finally synchronized, there may be some delays and other issues, but I don’t have time to investigate, but I can be sure that the editing of resources is currently supported (although the suffix of .drawio.svg has been modified to .svg, which causes vscode to fail The identified problem has not been resolved), so I will close this issue
