### ISSUE TITLE
vscode + joplin + webdav 

### ISSUE THREAD

**Issue by huaimingxiang** [rxliuli/joplin-vscode-plugin#16]
hello，what is joplin token？ how can I get  joplin token？
my joplin run on webdav，url is http or https。

**Comment by rxliuli** [comment]
ref link: https://joplinapp.org/clipper/

**Comment by huaimingxiang** [comment]
(intermediate value).filter is not a function

<img width="541" alt="image" src="https://user-images.githubusercontent.com/8815355/99210224-3e951200-2800-11eb-9e0e-969b2563376c.png">

**Comment by rxliuli** [comment]
Due to various problems, the official version of the vscode plugin does not support joplin v1.4. I will release a beta version that supports v1.4 later.

ref link: https://discourse.joplinapp.org/t/pre-release-1-4-is-now-available-for-testing-updated-14-11-20/12247/63

**Comment by rxliuli** [comment]
现在，我发布了 v0.2.0 的 beta 版本，你可以从 github 发布页面下载然后手动安装

**Comment by huaimingxiang** [comment]
收到，谢谢分享。

怀明祥
上海市  /  松江区
Email:  14333669@qq.com
Email:  kidhsks@hotmail.com
Phone:  17701767626
座右铭： 当你觉得处处不如人，不要自卑，记得你只是平凡人，做好自己的事情。
在 2020年11月17日 +0800 PM9:28，rxliuli <notifications@github.com>，写道：

**Comment by rxliuli** [comment]
> 收到，谢谢分享。 怀明祥 上海市  /  松江区 Email:  14333669@qq.com Email:  kidhsks@hotmail.com Phone:  17701767626 座右铭： 当你觉得处处不如人，不要自卑，记得你只是平凡人，做好自己的事情。 在 2020年11月17日 +0800 PM9:28，rxliuli <notifications@github.com>，写道：
> […](#)
> 现在，我发布了 v1.4 的 beta 版本，你可以从 github 发布页面下载然后手动安装 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯，另外。。。你的手机号显示出来了，最好删除吧 _(•̀ω•́ 」∠)_
