### ISSUE TITLE
No Notes Detected!

### ISSUE THREAD

**Issue by jt196** [rxliuli/joplin-vscode-plugin#17]
Hi there @rxliuli just to let you know, the VS Code plugin seems broken recently on my VS Code. It was working fine, but now it's gone. 

- The main window shows 'No notes detected!' as a warning message. 
- On startup I get this message: `(intermediate value).filter is not a function`
- If I try to refresh the screen, there is a warning message (bottom right) saying `this.folderList.forEach is not a function`

I noticed there's a program path in the preferences now, I don't remember seeing it there before. I've set it to:
- ~/Applications/
- ~/.joplin-bin

and just blank, the message still pops up, no notes found. 

Am I missing something? The web server is working fine, and as I mentioned, it was previously working. Seems like a recent update (to your plugin or Joplin) has broken it. I think I tested this 3-4 weeks ago and it was fine. I'm on dev version of Joplin - v 1.4.7.

James

**Comment by rxliuli** [comment]
ref: https://github.com/rxliuli/joplin-vscode-plugin/issues/16#issuecomment-727720528

**Comment by rxliuli** [comment]
v0.2.0 beta supports joplin v1.4
https://github.com/rxliuli/joplin-vscode-plugin/releases/tag/v0.2.0

  "configuration.joplin.programProfilePath": "Personal directory for joplin programs"

**Comment by Ethnical** [comment]
@rxliuli Yes it's works ! I had the same issue thanks for the pre-release stuff ! 👍
