### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by wookiesh** [rxliuli/joplin-vscode-plugin#18]
Hi, great plugin I love it 👍

Would you by any chance be looking at a way to copy paste images in documents like it's possible in Joplin ? 
I for sure could try to help :)

**Comment by rxliuli** [comment]
The function of adding images and attachments has been realized, which can be seen through the right-click menu

https://rxliuli.com/joplin-vscode-plugin/#/_navbar/get-started/configuration?id=paste-picture
