### ISSUE TITLE
Outline View [Feature Request]

### ISSUE THREAD

**Issue by jt196** [rxliuli/joplin-vscode-plugin#19]
Not played around with markdown in VSCode but I believe there's an outline view. How feasible would it be to have this kind of view in the Joplin pane at the bottom of the notes panel? 

This feature doesn't exist in Joplin and would be quite useful for navigating through longer notes.

**Comment by rxliuli** [comment]
Existing, you can use `> goto symbol` command to view the outline and jump

**Comment by rxliuli** [comment]
Project migration: https://github.com/rxliuli/joplin-utils/
