### ISSUE TITLE
clicking on a note opens it in a PDF viewer

### ISSUE THREAD

**Issue by alusiani** [rxliuli/joplin-vscode-plugin#2]
Hi,

I have the following installet packages on Fedora 32
- code-1.47.0-1594284094.el7.x86_64
  - rxliuli.joplin-vscode-plugin v0.1.2 (vscode extension)
- joplin-1.0.227-1.fc32.taw.x86_64

I enabled the web clipper on Joplin, I copied the Joplin token to vscode, I see the joplin notes in the vscode left joplin panel.

When I left-mouse-click a note, it opens up in okular (my default PDF viewer app I guess). I did not find yet a way to open the note in vscode.

**Comment by rxliuli** [comment]
https://joplinapp.org/faq/#how-can-i-edit-my-note-in-an-external-text-editor

**Comment by alusiani** [comment]
> https://joplinapp.org/faq/#how-can-i-edit-my-note-in-an-external-text-editor

Thanks and sorry for the noise. I have checked my associations but did not know that Joplin defined the default editor.

**Comment by alusiani** [comment]
Thanks and sorry for the noise. I have checked my associations but did not know that Joplin defined the default editor.
