### ISSUE TITLE
On Mac outline shows, but files are invisible 

### ISSUE THREAD

**Issue by victorkane** [rxliuli/joplin-vscode-plugin#21]
Thanks for such a great plugin!! 

Been using successfully both on Linux and Mac. On my MacBook Air, suddenly, outline of all folders are visible, but no notes appear. I get error message: `cannot read property 'map' of undefined`.

Have tried reloading, uninstalling and re-installing, but no files ever appear. Has this happened to anyone else? 

Thanks!

**Comment by rxliuli** [comment]
You need to install at least Joplin v1.4.19+, this is an incompatible update, please refer to: https://discourse.joplinapp.org/t/pre-release-1-4-is-now-available-for-testing-updated-23-11-20/12247
