### ISSUE TITLE
Tell people to activate Web Clipper

### ISSUE THREAD

**Issue by CWempe** [rxliuli/joplin-vscode-plugin#22]
I got the famous (?) `Joplin’s token/port is set incorrectly, unable to access Joplin service!` error message.

Of cause I found a few mentions via google that tell me to check `curl http://127.0.0.1:41184/ping`, wich returned `cannot connect`.

I think it would be very helpful to tell new users like me to activate the `Web Clipper` service inside the Joplin app. 😄 

As a Joplin newbee I had no idea

* there is a service inside the Joplin desktop app
* this service is disabled by default
* it is named Web Clipper
* it can be activated in the Web Clipper settings in side the desktop app

## So my suggestion

Add some thing like 

    Make sure you activated Web Clipper in the Joplin app.

to the documentation. <https://rxliuli.com/joplin-vscode-plugin/#/>

And the same for the first FAQ.

**Comment by rxliuli** [comment]
This is a blind spot, I did not notice this problem, I will add it to the document as soon as possible.  If you find any errors, please feel free to enlighten me.

**Comment by rxliuli** [comment]
I checked the documentation and it seems to have included this hint.

https://rxliuli.com/joplin-vscode-plugin/#/_navbar/get-started/quick-start?id=configure-plugin

**Comment by CWempe** [comment]
You are right. Can't argue with that. 😄 

I still would recommend to use the phrase "Web Clipper" in the plugin settings.
