### ISSUE TITLE
command 'joplinNote.refreshNoteList' not found

### ISSUE THREAD

**Issue by oshliaer** [rxliuli/joplin-vscode-plugin#24]
- [x] Joplin 1.4.19 (prod, linux)
- [x] Web clipper Service status: Ready on port 41184
- [x] rxliuli.joplin-vscode-plugin v0.3.1
- [x] `curl http://127.0.0.1:41184/ping` => `JoplinClipperServer%`
- [x] `code -v` => `1.52.1 x64`
- [x] Ubuntu 20.04

The extension returns error `command 'joplinNote.refreshNoteList' not found`

Any ideas?

**Comment by rxliuli** [comment]
1. try to install the latest vscode
2. reinstall joplin-vscode-plugin
3. restart vscode

**Comment by rxliuli** [comment]
I tried to integrate the error log analysis function, you can use this version

https://github.com/rxliuli/joplin-vscode-plugin/releases/tag/v0.3.2

**Comment by oshliaer** [comment]
OK. Solved

I downgrade the extension to the first release 03e8fa18f411f09c90d6272d866fd60a1a2bacf2 And I saw that it can't connect to `::1`. It means it can't resolve `127.0.0.1` or `localhost`.

I've added to my hosts the next line

#### /etc/hosts
`127.0.0.1       localhost.localdomain   big     localhost`

`big` just is the hostname.

Thanks for the support.

**Comment by rxliuli** [comment]
> OK. Solved
> 
> I downgrade the extension to the first release [03e8fa1](https://github.com/rxliuli/joplin-vscode-plugin/commit/03e8fa18f411f09c90d6272d866fd60a1a2bacf2) And I saw that it can't connect to `::1`. It means it can't resolve `127.0.0.1` or `localhost`.
> 
> I've added to my hosts the next line
> 
> #### /etc/hosts
> `127.0.0.1 localhost.localdomain big localhost`
> 
> `big` just is the hostname.
> 
> Thanks for the support.

Can you add it to the FAQ document?
https://github.com/rxliuli/joplin-vscode-plugin/blob/dev/docs/_navbar/get-started/faq.md

> I don’t use Linux, so I might not encounter this problem
