### ISSUE TITLE
403 status code error upon attempting to open Joplin outline on mac

### ISSUE THREAD

**Issue by victorkane** [rxliuli/joplin-vscode-plugin#26]
Hi there! With latest release 0.3.1 installed on mac, latest joplin and latest vscode versions, I get error 

`Request failed with status code 403` 

upon attempting to open outline in Joplin view. Please help, thanks!

**Comment by rxliuli** [comment]
Please check if the web clipper service is turned on normally

https://rxliuli.com/joplin-vscode-plugin/#/_navbar/get-started/faq

**Comment by victorkane** [comment]
Thanks, but I have been using the plugin for months, and never attempt to access vs code without joplin (and clipper service which I have on permanently) running. What happened here is weird:

1. I ran vscode without first running Joplin, and got the error.
2. I realized Joplin wasn't running, and ran it.
3. Even reloading, or restarting vs code several times didn't revert the situation.
4. After restarting the machine, running Joplin and then vs code, things returned to normal.

So it was my bad, but I do find it weird that running joplin and restarting vs code didn't revert the situation. However, I now cannot reproduce the error, so please close this issue if you cannot either.

Thanks again for a great plugin that I use every day! When I get some spare cash, will be donating!
