### ISSUE TITLE
Clicking a note opens an external editor

### ISSUE THREAD

**Issue by Hudler** [rxliuli/joplin-vscode-plugin#27]
Hello,

I just installed Joplin (1.5.14) and this extension (0.3.1) to vscode (1.45.1) on my ubuntu (18.04).

I see the notebooks and notes however, when I try to open a note, the note is opened using an external editor (gedit).

How do I edit the note directly in vscode?

**Comment by rxliuli** [comment]
ref link: https://rxliuli.com/joplin-vscode-plugin/#/_navbar/get-started/faq?id=not-opened-in-vscode-after-clicking

**Comment by rxliuli** [comment]
duplicate: https://github.com/rxliuli/joplin-vscode-plugin/issues/2

**Comment by Hudler** [comment]
My text editor command is now code -r and it works as expected. Couldn't this be mentioned in the docs?

**Comment by rxliuli** [comment]
> My text editor command is now code -r and it works as expected. Couldn't this be mentioned in the docs?

Yes, but my system default markdown editor is vscode, so I didn't notice this problem. If you wish, you are welcome to modify the document [Quick start](https://github.com/rxliuli/joplin-vscode-plugin/blob/dev/docs/_navbar/get-started/quick-start.md)
