### ISSUE TITLE
VSCode-Insiders

### ISSUE THREAD

**Issue by thwaller** [rxliuli/joplin-vscode-plugin#28]
Is this plugin compatible with VSCode-Insiders? I recently upgraded to this version and the plugin no longer works.

**Comment by rxliuli** [comment]
I have never used the insider version. There may indeed be some compatibility issues. Perhaps, I can choose to fall back to the stable version?

**Comment by thwaller** [comment]
Going back to Code vs Cove-Insiders is not an option. The move was made to gai naccess to the additional features. I believe the issue is that the regular version name is `code`, and the insiders is `code-insiders`. I see in the plugin code that the program `code` is referenced. I will see if I can test that, I just need to see how the code is added to VSCode first.

**Comment by rxliuli** [comment]
I simply checked the code insiders. After setting the token, it looks normal. Is there any more detailed error information?
![image](https://user-images.githubusercontent.com/24560368/104532630-9d81d680-564b-11eb-883c-80a111428bdc.png)

**Comment by thwaller** [comment]
Sorry, I did not notice your comment until I got the notification you closed this. I understand this will not be addressed, and is not compatible with the Insiders version of the VS Code project. This might be worth noting on the extension page though... I have not seen any other extensions with this issue.

**Comment by rxliuli** [comment]
> Sorry, I did not notice your comment until I got the notification you closed this. I understand this will not be addressed, and is not compatible with the Insiders version of the VS Code project. This might be worth noting on the extension page though... I have not seen any other extensions with this issue.

I haven't really used the insiders version, so I'm not sure if there are any internal details changes, but I don't intend to be compatible with it. There are too many possibilities for the nightly build

**Comment by thwaller** [comment]
No problem, I understand. It is basically the beta version of VS Code, like there is google-chrome and google-chrome-beta... this is vscode-insiders vs vscode. There are also some additional features that exist that do not exist in the stable release. The insiders version is released daily and offers faster release of new features and bug fixes.

I am not sure on the specifics of the differences as it relates to extensions, but I have not seen any other extensions that work one one and not the other. HEre is some general information:  
https://code.visualstudio.com/blogs/2016/05/23/evolution-of-insiders

I understand your position, no worries. I might only suggest that this be noted on the extension details. I have 73 extensions that I use and all of them work in both  the normal and insiders, so this is something that is quite specific to your extension that I would want to know as a user, so I am not taking time trying to figure out why there are issues.
