### ISSUE TITLE
VSCode multiple code bouncing macos

### ISSUE THREAD

**Issue by rhysjtevans** [rxliuli/joplin-vscode-plugin#29]
Hi @rxliuli, great work on the plugin!
I'm trying to use it on a Mac with multiple desktops and multiple maximized VSCode windows. 

I've tried 
- changing the default editor on MacOS to VSCode
- changed the editor to `code -r` in joplin itself
The best case is the second option where the note is opened up in the last used VSCode window but MacOS flicks back to my desktop. Feels a bit cumbersome / offputting to use.

Is there a way around this where the plugin opens the note directly in the same vscode window using the vscode api?
Presumably your calling an API for joplin to open the note in an external editor which feels a bit of an anti pattern.
Alternatively is there any support for interacting with the Nextcloud joplin web api or something else e.g the joplin server directly?

**Comment by rxliuli** [comment]
> The best case is the second option where the note is opened up in the last used VSCode window but MacOS flicks back to my desktop. Feels a bit cumbersome / offputting to use.

I have never used macos, so I have never encountered this kind of problem. But it should be possible to support it by modifying the joplin api.

> Alternatively is there any support for interacting with the Nextcloud joplin web api or something else e.g the joplin server directly?

As long as their http api is compatible with the existing joplin web clipper api, it can easily support: https://joplinapp.org/api/references/rest_api/

**Comment by rxliuli** [comment]
Can you add a gif or video presentation?

**Comment by rhysjtevans** [comment]
Sorry @rxliuli I've left the company and handed the macbook back in. I'll be buying another soon so will be able to record it then

**Comment by rxliuli** [comment]
Is there more information, if not, I will close it.
