### ISSUE TITLE
打开笔记不开心的窗口

### ISSUE THREAD

**Issue by seanlook** [rxliuli/joplin-vscode-plugin#33]
我装好这个插件之后，能看到joplin里面的笔记列表了，但点击笔记标题时，每次都是在新的vscode窗口打开，感觉会开太多窗口，而且打开稍慢了些。是否可以在当前窗口的一个标签页打开
vscode 版本 v1.54.2

**Comment by rxliuli** [comment]
默认应该是在当前窗口打开的，你试试从 joplin 那边点击从外部编辑器打开的行为是什么？

**Comment by rxliuli** [comment]
参考：https://segmentfault.com/q/1010000006131199

**Comment by seanlook** [comment]
试了下，把外部编辑器设置为 vscode，就没问题了。在 vscode joplin 插件里编辑，会在当前 tab 中打开。
如果把外部编辑器设置为typora，在 vscode 里面点击标题，会自动打开 typora。这个与使用 vscode 又有点违背，倒是可以给插件提供一个选项，是否默认用外部编辑器模式。

**Comment by rxliuli** [comment]
是的，目前这个限制来源于一个未公开的 joplin rest api，没有可以仅监视而不在外部编辑器打开笔记的 api。。。
ref：https://github.com/rxliuli/joplin-utils/blob/a35d8e621a38dbb9dc7fcdac4a7df0c695717d6e/libs/joplin-api/src/api/NoteActionApi.ts#L10

**Comment by rxliuli** [comment]
> 我装好这个插件之后，能看到 joplin 里面的笔记列表了，但点击笔记标题时，每次都是在新的 vscode 窗口打开，感觉会开太多窗口，而且打开稍慢了些。是否可以在当前窗口的一个标签页打开
> vscode 版本 v1.54.2

另外打开稍慢的问题可以通过更新 VSCode 来解决，最新版本感觉上快了一些

![test (5)](https://user-images.githubusercontent.com/24560368/111127406-c8869900-85ae-11eb-9e8e-2708d69e5522.gif)

**Comment by seanlook** [comment]
good，感谢这么好的插件
