### ISSUE TITLE
vscode安装插件后joplin页面的md文档无法在vscode编辑器中直接打开

### ISSUE THREAD

**Issue by sunerpy** [rxliuli/joplin-vscode-plugin#34]
如果设置md文件的默认打开程序是vscode的话，会生成一个新的终端窗口打开文件。
但是在vscode中，不通过joplin插件的时候，是可以在编辑器中直接打开md文件的，并不需要设置默认应用程序之类的

**Comment by rxliuli** [comment]
检查使用 vscode 命令行打开 md 文件的行为是什么，如果也是打开一个新窗口，则需要检查 vscode 的设置，可能与配置项 `Open Files In New Window` 有关联

```sh
code .\README.md
```

**Comment by rxliuli** [comment]
看起来很久没有活动，我将暂时关闭它，如果有任何问题，欢迎重新打开
