### ISSUE TITLE
Publishing to open-vsx

### ISSUE THREAD

**Issue by harshcurious** [rxliuli/joplin-vscode-plugin#35]
I would love to be able to use your extension on [VSCodium](https://vscodium.com/). Could you also publish your extension to the more open extension marketplace [open-vsx](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)? Shouldn't be too hard there is a [GitHub action](https://github.com/HaaLeo/publish-vscode-extension) available to completely automate the process.

**Comment by rxliuli** [comment]
Someone mentioned this before, ref: https://discourse.joplinapp.org/t/joplins-vscode-plugin-is-released/9624/66?u=rxliuli
