### ISSUE TITLE
如果使用vscode的remote插件进行远程开发，插件被安装在远程主机上导致找寻joplin失败

### ISSUE THREAD

**Issue by longforrich** [rxliuli/joplin-vscode-plugin#36]
是不是提供设置ip的功能或者在本地vscode执行,感觉前者更容易些

**Comment by rxliuli** [comment]
你需要在 remote 主机上安装 joplin 才行

**Comment by rxliuli** [comment]
关联：https://github.com/rxliuli/joplin-vscode-plugin/issues/39

**Comment by rxliuli** [comment]
Project migration: https://github.com/rxliuli/joplin-utils/

**Comment by rxliuli** [comment]
Project migration: https://github.com/rxliuli/joplin-utils/
