### ISSUE TITLE
【特性需求】希望增加目录浏览

### ISSUE THREAD

**Issue by maquedexiju** [rxliuli/joplin-vscode-plugin#38]
插件本身具有很多实用功能，非常感谢！
希望能够增加目录浏览的功能，类似 VSCode 自带的 “OUTLINE”，不知是否可以实现

![image](https://user-images.githubusercontent.com/6948576/115189353-e8aef800-a118-11eb-96d7-117960cfd19f.png)

**Comment by rxliuli** [comment]
事实上，vscode 已经有功能支持这个操作了。
ref：https://github.com/rxliuli/joplin-vscode-plugin/issues/19

**Comment by maquedexiju** [comment]
这个功能我是知道的，但是我是希望目录能够常驻，而且层级能够更清晰一些，目前的这个 goto symbol 感觉还是不够清晰
