### ISSUE TITLE
Support remote Web clipper servers

### ISSUE THREAD

**Issue by 3v1n0** [rxliuli/joplin-vscode-plugin#39]
**Describe the bug**

A Web Clipper can be in any location, not only in `localhost`, especially when using `joplin` terminal app in headless mode

**To Reproduce**

Go to joplin extension settings -> Set Web Clipper hostname
- No option available

**Expected behavior**

An hostname configuration option is available.

**Comment by rxliuli** [comment]
joplin-vscode-plugin does not support terminal applications, please refer to: https://github.com/rxliuli/joplin-vscode-plugin/issues/37

**Comment by 3v1n0** [comment]
Mh, I see, well having it to support a remote server would be quite nice to basically to just use vscode to handle the notes (minus resources) without having to install and keep running the desktop client

**Comment by rxliuli** [comment]
In fact, whether to open a note or open an attached resource, you need to use the action api (an undisclosed api). Although you can manually monitor the temporary file modification and use noteApi/resourceApi to save the modification here, this is not currently done, so you must rely on the local Joplin desktop version. I may try to be compatible with remote after waiting for the official release of Joplin Server.

**Comment by rxliuli** [comment]
action api ref: https://discourse.joplinapp.org/t/hope-that-the-web-api-adds-the-following-features-to-support-the-development-of-third-party-extensions/9277/7

**Comment by 3v1n0** [comment]
> Although you can manually monitor the temporary file modification and use noteApi/resourceApi to save the modification here, this is not currently done, so you must rely on the local Joplin desktop version.

I see, that would be nice to have as it would make handling the editing easier and be able to just run the server without the whole UI.

**Comment by rxliuli** [comment]
Project migration: https://github.com/rxliuli/joplin-utils/
