### ISSUE TITLE
A command 'Upload image from clipboard' doesn't work on windows 10.

### ISSUE THREAD

**Issue by tortoise5k** [rxliuli/joplin-vscode-plugin#42]
When I ran a command 'Upload image from clipboard', nothing happened.
The following is a result of test uploading images from clipboard.

```sh
$ npx jest -t '测试从剪切板上传图像'
 FAIL  test/util/UploadResourceUtil.test.ts
  ● 测试 UploadResourceUtil › 测试从剪切板上传图像

    spawn powershell ENOENT
```

`spawn powershell ENOENT` seems to mean that `powershell` command doesn't exist.
To solve this problem, I added a value to an environment variable.
`PATH : C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe`
I couldn't find a document about default environment variables in microsoft official documents.
Is a command 'Upload image from clipboard' available on windows 10 by default?

**Comment by rxliuli** [comment]
> When I ran a command 'Upload image from clipboard', nothing happened.
> The following is a result of test uploading images from clipboard.
> 
> ```shell
> $ npx jest -t '测试从剪切板上传图像'
>  FAIL  test/util/UploadResourceUtil.test.ts
>   ● 测试 UploadResourceUtil › 测试从剪切板上传图像
> 
>     spawn powershell ENOENT
> ```
> 
> `spawn powershell ENOENT` seems to mean that `powershell` command doesn't exist.
> To solve this problem, I added a value to an environment variable.
> `PATH : C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe`
> I couldn't find a document about default environment variables in microsoft official documents.
> Is a command 'Upload image from clipboard' available on windows 10 by default?

It is not provided or impossible to provide, uploading is divided into two steps

1. Get the cut version of the picture through the command line
2. Upload pictures via joplin api

**Comment by rxliuli** [comment]
You can try to enter `powershell` in CMD. If there is no error, you should be able to use the screenshot normally. If an error occurs, you need to install powershell.

ref: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.1

![image](https://user-images.githubusercontent.com/24560368/115563663-5d855c00-a2ea-11eb-8b08-dfa7dd773601.png)

**Comment by rxliuli** [comment]
I added a FAQ: https://rxliuli.com/joplin-vscode-plugin/#/_navbar/get-started/faq?id=windows-10-cannot-upload-a-cut-version-of-the-picture

**Comment by tortoise5k** [comment]
>When I ran a command 'Upload image from clipboard', nothing happened.
>The following is a result of test uploading images from clipboard.
>
>$ npx jest -t '测试从剪切板上传图像'
> FAIL  test/util/UploadResourceUtil.test.ts
>  ● 测试 UploadResourceUtil › 测试从剪切板上传图像
>
>    spawn powershell ENOENT
>spawn powershell ENOENT seems to mean that powershell command doesn't exist.
>To solve this problem, I added a value to an environment variable.
>PATH : ~~C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe~~
>I couldn't find a document about default environment variables in microsoft official documents.
>Is a command 'Upload image from clipboard' available on windows 10 by default?

The value of the environment variable was wrong, the correct value is `C:/Windows/System32/WindowsPowerShell/v1.0`
.

**Comment by tortoise5k** [comment]
>You can try to enter powershell in CMD. If there is no error, you should be able to use the screenshot normally. If an error occurs, you need to install powershell.

I tried it, there was no error.
In my environment, powershell command could not be executed because the environment variable was not set.
