### ISSUE TITLE
Feature Request: Allow for Moving Notes in the All Notes View

### ISSUE THREAD

**Issue by zersiax** [rxliuli/joplin-vscode-plugin#43]
The integration with Visual Studio Code has a lot to advantages for me as a blind developer and it makes the app quite a bit nicer to work with. 
It would be even better if I was able to move notes around in the treeview of all notes, CherryTree style, e.g. move notes between various levels/folders/notebooks with the keyboard.
It would be awesome if that can be looked into.

**Comment by rxliuli** [comment]
At present, moving is not a big trouble, because in fact I can't realize dragging and moving, but maybe it can support right-click and keyboard forms. . .

Reference limit: https://rxliuli.com/joplin-vscode-plugin/#/_navbar/get-started/limitations

**Comment by zersiax** [comment]
Right. I was mostly thinking, say, ctrl+x and ctrl+v or so to cut and paste a note from one place in the hierarchy to another, or using a command pallet command to essentially select a new location for the selected note. Either of those would already help immensely.

**Comment by rxliuli** [comment]
I'm looking for a better way to implement interaction. Can you check the voting here?
https://discourse.joplinapp.org/t/which-of-the-following-two-types-of-ux-do-you-think-is-better/17379

**Comment by rxliuli** [comment]
Published 0.5.0

https://github.com/rxliuli/joplin-utils/releases/tag/joplin-vscode-plugin%400.5.0

**Comment by zersiax** [comment]
This is great, thanks. It only seems to work when I use the right-click menu, though.
If I try ctrl+x and ctrl+v, which should be the keybindings, I only get a message that " contributed command joplin.paste failed".  Not sure if I can get more verbose logging for debugging purposes?

**Comment by rxliuli** [comment]
Can you try this? If an error occurs, it will add detailed error information to the **Output** panel. Can you post this information here?

[joplin-vscode-plugin-0.5.1.zip](https://github.com/rxliuli/joplin-vscode-plugin/files/6516450/joplin-vscode-plugin-0.5.1.zip)
