### ISSUE TITLE
Plugin no longer works with most recent version of Joplin from the AUR

### ISSUE THREAD

**Issue by SweetestRug** [rxliuli/joplin-vscode-plugin#44]
- [x] I checked [FAQ](https://rxliuli.com/joplin-vscode-plugin/#/_navbar/get-started/faq)

**Describe the bug**
On installing the most recent version of joplin-appimage from the AUR (version 2.0) notes can be seen in the sidebar, but the notes themselves cannot be opened

**To Reproduce**
Install joplin-appimage from the AUR
Load vscode
Click on a note
The content of the note does not load

**Expected behavior**
The note contents can be seen/edited

**Desktop (please complete the following information):**

- OS: Linux (Manjaro)
- Joplin platform-version: Desktop 2.0 [Beta]
- VSCode version latest
- joplin-vscode-plugin version latest

**Comment by rxliuli** [comment]
I have not used Joplin 2.0, but I will try it later

**Comment by ncatanchin** [comment]
I ran into this problem, using latest version of Joplin on Windows 10.  

* My file associations were configured to open `*.md` files in Notepad++
* Clicking on a note in VSCode was opening the note in Notepad++
* Changing the file associations did not appear to fix the problem - but may have been a contributing factor, as:

✅ Updating my Joplin configuration, which had Notepad++ as well as the **Text editor command** did solve the problem

![image](https://user-images.githubusercontent.com/2169122/118566424-2e61ed80-b7b7-11eb-9a86-7e0801e487f8.png)

**Comment by SweetestRug** [comment]
Thanks @ncatanchin. I have no idea _why_ adding my path to vscode worked, but it now works!
