### ISSUE TITLE
Thanks for such a good plugin, can this feature [Find & Replace in All Notes] be realized?

### ISSUE THREAD

**Issue by testiting** [rxliuli/joplin-vscode-plugin#45]
Thanks for such a good plugin, can this feature [Find & Replace in All Notes] be realized?
[https://discourse.joplinapp.org/t/find-replace-in-all-notes/1740](https://discourse.joplinapp.org/t/find-replace-in-all-notes/1740)

**Comment by rxliuli** [comment]
It cannot be done at present, vscode itself does not support the extended Search function, and this operation is very dangerous and must be replaced in a visual way. . . Having said that, I have not encountered a scene that requires this kind of operation. Can you briefly talk about your actual use scene?

**Comment by testiting** [comment]
There is a possible way to implement at present, vscode currently can find and replace all opened edit files. At the same time, the joplin-vscode-plugin can already query all the notes of a certain keyword. If the joplin-vscode-plugin can open all the files with this keyword at once [with a command], the rest can be handled by vscode.  A possible use case is that multiple notes have some duplicate keywords, and replacing them one by one is sometimes troublesome.

**Comment by rxliuli** [comment]
> If the joplin-vscode-plugin can open all the files with this keyword at once [with a command], the rest can be handled by vscode.

This function can be implemented, but I will not do it, because it puts too much pressure on the performance of VSCode and Joplin, and opening 1000 files at the same time VSCode will probably freeze, and Joplin's file monitor may also lose data. However, I may complete a web page later to do this.

**Comment by testiting** [comment]
Yes, you are right. In some extreme cases [such as the 1000 files you mentioned], it will cause performance problems. The above method is only suitable for some common situations [such as the case of a small number of files]. Anyway, appreciate your development work and look forward to your web solutions, thanks！
