### ISSUE TITLE
Show title of the note [Feature Request]

### ISSUE THREAD

**Issue by laggingreflex** [rxliuli/joplin-vscode-plugin#46]
Show the title of the note instead of "edit-xxxxxxxx". 

![image](https://user-images.githubusercontent.com/2523987/119370706-351ac400-bcd3-11eb-99bb-06af82905161.png)

Really nice extension!

**Comment by rxliuli** [comment]
Can't do it at present, please refer to: https://joplin-utils.rxliuli.com/joplin-vscode-plugin/guide/limitations.html, In addition, the project has been migrated to [joplin-utils monorepo](https://github.com/rxliuli/joplin-utils)
