### ISSUE TITLE
New feature: Copy Markdown link

### ISSUE THREAD

**Issue by JonathanPlasse** [rxliuli/joplin-vscode-plugin#7]
Hi,
Awesome extension.
I would love to have the possibility to copy markdown link from other notes and not having to switch back to Joplin to do so.
Thanks

**Comment by rxliuli** [comment]
It has been supported to copy the link of the note and render it correctly in the markdown preview at the same time. It can also jump to the corresponding note when clicked, but there is still a problem with Ctrl+Click in the editor, which needs to be fixed. . .

https://github.com/rxliuli/joplin-vscode-plugin/releases/tag/v0.1.6
