### ISSUE TITLE
Open Joplin view with a keybinding

### ISSUE THREAD

**Issue by rasulkireev** [rxliuli/joplin-vscode-plugin#9]
In VS Code you can create keybindings to acess certain parts of the app. For example, if you want to access the file explorer you can do this:

```javascript
    {
        "key": "cmd+k cmd+p",
        "command": "workbench.view.explorer"
    },
```

you can now access explorer with CMD+P. Or to access the Version Control, you can do:

```javascript
    {
        "key": "cmd+k cmd+v",
        "command": "workbench.view.scm"
    },
```

Can I create such keybinding for joplin view? For example,

```javascript
{
  "key": "cmd+k cmd+j"
  "command": "workbench.view.joplin"
}
```

**Comment by rxliuli** [comment]
I know, but one of the reasons why I haven't created too many shortcuts is that I use the keymap of jetbrains idea, so what I need is a shortcut that is compatible with both vscode/jetbrains idea.  .  .

**Comment by rasulkireev** [comment]
I see, this makes sense. I'm not too familiar with JetBrains and its shortcuts, but can imagine it might be hard to create shotcuts for both.

What do you mean by "the keymap of idea"?

I have no knowledge of creating vs code plugins. I'll try to do some exploration and will try to get a PR going.

**Comment by rxliuli** [comment]
@rasulkireev Idea here == jetbrains idea

**Comment by rasulkireev** [comment]
I figured it out. For VS Code users, you can do one of the following:

1. In `keybindings.json` add this:

```
{
  "key": "cmd+k cmd+j"
  "command": "workbench.view.extension.joplin-note"
}
```

2. Open the Keyboard Shortcut UI (Shift+CMD+P, then enter Shortcuts). Search for joplin and you will have a view of different joplin related commands. You can manually create shortcuts for each action.
